### ISSUE TITLE
默认账号密码问题

### ISSUE THREAD

**Issue by ritaswc** [zoom-ci/zoom-ci#1]
默认账号密码
admin
123456
非常容易出问题

可否考虑第一次打开时，强制用户设置新密码
不使用 默认的密码123456  这一策略

很容易引起大规模问题

**Comment by rleecn** [comment]
已在[版本 v1.0.2](https://github.com/zoom-ci/zoom-ci/releases/tag/v1.0.2)增加，感谢提出。
